coverage:
  range: 50..90
  round: down
  precision: 0
  status:
    project:
      default:
        threshold: 50%  # allow coverage to drop by up to 50% in a PR before marking it failed
  
comment:
  layout: "diff, files"
