name: Tests

on:
  push:
    branches:
      - master
      - tiger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        dockerfile: docker/Dockerfile
        tag_with_ref: true
        tag_with_sha: true
        always_pull: true
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: chtcuw/chtc-bot
